### ISSUE TITLE
Chunks keep being loaded after initial generation

### ISSUE THREAD

**Issue by tyra314** [APengu/LostThaumaturgy#15]
Minecraft: 1.11.2
Forge: 13.20.0.2315
LostThaumaturgy: 7b
HammerCore: 1.8.4

It seems that chunks generated once mostly stay loaded. Verified this with ChickenChunks in an instance with only ChickenChunks and LostThaumaturgy loaded. See attachment:

![chunks](https://user-images.githubusercontent.com/16997177/26979754-321749fc-4d30-11e7-9666-945810e7801a.png)

You can clearly see the path I took after world gen. These chunks will also be loaded after a restart.
Just to be clear that is an serious issue, as it cripples down any server or SSP in the long run.

**Comment by APengu** [comment]
leaving ONLY Hammer Core and Lost Thaumaturgy

**Comment by tyra314** [comment]
And how should I verify that it happens without ChickenChunks? Besides that, there is no other mod.

**Comment by APengu** [comment]
idk, it doesn't happen on my server tho...

**Comment by tyra314** [comment]
How do you now, it doesn't happen then?

**Comment by APengu** [comment]
because I have really weak PC and there are thousands of explored chunks

**Comment by APengu** [comment]
Soo... any news about this situation?

**Comment by tyra314** [comment]
I just tested the new version. Seems fixed, no idea what changed. Downgrading to the old version and it still happens. ¯\\\_(ツ)_/¯

**Comment by APengu** [comment]
Hm.. Okay. I seems like it was a thing with aura. :/
Anyway it is fixed so i don't care :)
