### ISSUE TITLE
Wand of Item Freeze NPE

### ISSUE THREAD

**Issue by sandalle** [APengu/LostThaumaturgy#17]
When trying to use a Wand of Item Freeze, I get a Null Pointer Exception (NPE). I spawned it in via cheat (Just Enough Items item cheat, still in survival mode).

Crash report: [crash-2017-06-20_12.00.47-client.txt](https://github.com/APengu/LostThaumaturgy/files/1089365/crash-2017-06-20_12.00.47-client.txt)

**Comment by APengu** [comment]
Fixed

**Comment by sandalle** [comment]
Thanks for the quick fix! :)
