### ISSUE TITLE
Thaumic Slimes spawn too frequently and during the day

### ISSUE THREAD

**Issue by sandalle** [APengu/LostThaumaturgy#18]
I'm not sure if this intentional or not, and if it is a config option to tone it down would be awesome ;), but the Thaumic Slimes are a huge nuisance. They spawn during the day (ignoring light levels for hostile monsters) and spawn fairly frequently (I often see three or more wherever I go during the day time).

**Comment by omgNaj** [comment]
Agreed. They (and wisps) are everywhere. The wisps are a nuisance because they make so much noise and pretty soon they're sitting on every fence post of your yard. The slimes are game-breaking imo as they are hostile and spawn in your 'safe' areas.

**Comment by APengu** [comment]
Mobs don't spawn, at all. For now.
