### ISSUE TITLE
[MC 1.11.2] Lost Thaumaturgy 10r java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by sandalle** [APengu/LostThaumaturgy#19]
I was crafting TInker's Construct Grout in a Tinker's Construct Crafting Station, another player taking coal out furnaces to make a torch, and I don't know what the third player was doing (he's four ;)).

crash-report: [crash-2017-06-24_20.52.58-server.txt](https://github.com/APengu/LostThaumaturgy/files/1100126/crash-2017-06-24_20.52.58-server.txt)

**Comment by cursinorock** [comment]
Same here
Я тоже

**Comment by sandalle** [comment]
Here's another one with a wisp ticking: [crash-2017-07-19_18.23.28-server.txt](https://github.com/APengu/LostThaumaturgy/files/1160884/crash-2017-07-19_18.23.28-server.txt)

**Comment by APengu** [comment]
Fixed in 13r.
