### ISSUE TITLE
I just made a version of Chinese, translated by myself.

### ISSUE THREAD

**Issue by yqmtat** [APengu/LostThaumaturgy#20]
Here are the lang files of simplified and traditional Chinese. 
5 hours of mannual typing, 1h of proofreading, less than 1％ of mistake:)
(original)
[Chinese lang.zip](https://github.com/APengu/LostThaumaturgy/files/1117831/Chinese.lang.zip)

How can I upload it?

**Comment by yqmtat** [comment]
I also noticed there is a typo in US version:
hastle-----hassle

**Comment by APengu** [comment]
Okay, imported
