### ISSUE TITLE
Ticking Entity exception:  Lost Thaum getDrops event

### ISSUE THREAD

**Issue by archonsd** [APengu/LostThaumaturgy#21]
I think this was i.r.t. Lost Thaum, based on the exception output.

I'd just had a creeper explode in front of me when the crash happened.  Based on the stack trace, I suspect the creeper may have been trying to drop a Lost Thaum-related item?  Otherwise, I didn't see a chest nearby, but maybe the creeper's explosion caught a loot chest somewhere.  I was in a very tight tunnel and didn't see much around me when it exploded, but it took out a lot of walls, etc., so it could've gotten a chest I didn't know what around.  Otherwise, I had a Lost Thaum drop on me (a sword of somesort) that I'm not sure where I got it, but maybe the creeper killed me and that sword was the drop in question?  

Either way..  This was a 1.11.2 SMP server that crashed.. latest release Forge, latest Lost Thaum.

Full trace at pastebin:  https://pastebin.com/unicfPTY

**Comment by archonsd** [comment]
Had another hit on this same issue.  Figured I'd log it too.

https://pastebin.com/HEhLHQtJ

**Comment by APengu** [comment]
Duplicate to #19
