### ISSUE TITLE
[1.12] Broken textures

### ISSUE THREAD

**Issue by Blatts12** [APengu/LostThaumaturgy#24]
I think this is optifine issue.

http://i.imgur.com/P3JpiCw.png

**Comment by Denoknight** [comment]
I can confirm that this happens without optifine.

**Comment by APengu** [comment]
Try to launch only LT and HC.

**Comment by Blatts12** [comment]
with only LT and HC txts are fine but when i add jei txts are broken

**Comment by APengu** [comment]
I wonder what does JEI make with textures anyway...

**Comment by SpaghettiSauce** [comment]
I'm having the same issue, but with only LT and HC.
![brokentextures](https://user-images.githubusercontent.com/31096465/29407532-50767926-830a-11e7-88e6-e5d95783b72b.png)

**Comment by APengu** [comment]
Fixed. Wait till 13r
