### ISSUE TITLE
"Cascading world generation lag"

### ISSUE THREAD

**Issue by Darkmega18** [APengu/LostThaumaturgy#26]
I'm getting a lot of these in my console window:

[B#349]  [18:17:12] [Server thread/WARN] [FML]: Lost Thaumaturgy loaded a new chunk (153, 143  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [18:17:12] [Server thread/WARN] [FML]: Lost Thaumaturgy loaded a new chunk (152, 142  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [18:17:14] [Server thread/WARN] [FML]: Lost Thaumaturgy loaded a new chunk (158, 151  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [18:17:14] [Server thread/WARN] [FML]: Lost Thaumaturgy loaded a new chunk (157, 151  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [18:17:14] [Server thread/WARN] [FML]: Lost Thaumaturgy loaded a new chunk (156, 150  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

My world generation was being incredibly slow and your mod came up the most until I ended the game early cause it was doing too much. Are you able to fix that or know what's causing it?
it didn't crash or anything. it just kept giving me these messages.

**Comment by APengu** [comment]
This was fixed. Just not yet released.

**Comment by Darkmega18** [comment]
Roger that.
