### ISSUE TITLE
The magic book can't read .

### ISSUE THREAD

**Issue by gxy17886** [APengu/LostThaumaturgy#28]
Look at this picture: http://imgur.com/PImH7Ij http://imgur.com/a/LKkaV.
magic book only read directory，can‘t read other pages。version：LostThaumaturgy-1.12.1-13r.jar。HammerCore-1.12-1.9.4.0.jar。forge1.12.1-14.22.0.2459

**Comment by APengu** [comment]
You have to research them first

**Comment by gxy17886** [comment]
thanks
