### ISSUE TITLE
[1.12.1]Chinese localization text display problem

### ISSUE THREAD

**Issue by gxy17886** [APengu/LostThaumaturgy#30]
Chinese localization on the manual does not wrap correctly and can not display all the text。。I add 
 "\n"'or`<br>`'" into the zh_CN.lang..But also have this problem .Other MODs can use "\n"'or`<br>`'"  wrap word .

picture here： http://imgur.com/a/m34GZ

**Comment by APengu** [comment]
you just have to use space character " " and it will wrap if text after space couldn't fit
