### ISSUE TITLE
Translation problem （zh_CN)

### ISSUE THREAD

**Issue by limuness** [APengu/LostThaumaturgy#32]
In mainland China,this cannot be the same translation as Taiwan，
because of the thaumcraft,Taiwan's translator is 60% different from the mainland，
for example，Thaumcraft，in Taiwan they call them 秘术时代，but in mainland china，
they call 神秘时代.So don't use zh_TW  after Google translate and put it in CH_CN,
I put the correct translation in 1.11.2 lang，and I will update it.

**Comment by APengu** [comment]
then make pull request to 1.12.1 branch
