### ISSUE TITLE
Question About Another Mod 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [APengu/LostThaumaturgy#39]
So the creator of ATLCandles mod is running into an error and I like his concept but coding skills needs work ... what causes this error?

https://github.com/AllTheLayers/ATLCraftCandlesMod/issues/10

I am asking for your help because you are an advanced coder.

**Comment by APengu** [comment]
You have a method that uses client-only classes. Annotate the method with @SideOnly(Side.CLIENT)
in some block classes, and it should fix it
