### ISSUE TITLE
Crash NPE during WorldGen

### ISSUE THREAD

**Issue by tyra314** [APengu/LostThaumaturgy#4]
I get a crash:

https://gist.github.com/tyra314/cc087513aad03acffebe0c46a7c49ad7

Minecraft: 1.11.2
Forge: 13.20.0.2285
Version: LostThaumaturgy_1.11.2-1b.jar

**Comment by APengu** [comment]
Thanks! Gonna fix it ;)

**Comment by APengu** [comment]
Fixed in 2b
