### ISSUE TITLE
GPL violation with jPaste

### ISSUE THREAD

**Issue by quat1024** [APengu/LostThaumaturgy#41]
It looks like this library: https://github.com/APengu/LostThaumaturgy/tree/1.12.1/src/main/java/com/pengu/lostthaumaturgy/jpaste

is copied and pasted from here: https://github.com/BrianBB/jPastebin

jPastebin is licensed under the GNU General Public License, which requires you to give attribution. I don't see any, either in the README or on Curse. Whoops.

**Comment by quat1024** [comment]
On that note, btw, shouldn't you be disclosing somewhere that you're uploading crashes to Pastebin and apparently Discord? Logs can contain potentially personally identifiable information (contents of chat, computer hardware, username) that people may not want to be made public. I don't think you have a privacy policy.

**Comment by APengu** [comment]
I wanted to remove that jPastebin for a long time, and I finally did it, so I removed it and made the mod a bit less.
The crashes don't provide logs, only the report AND you can turn this feature off. I'm going to make a popup in a main menu for that.

**Comment by APengu** [comment]
![image](https://user-images.githubusercontent.com/10291214/30771152-559515e6-a049-11e7-85e0-c5c8e01ca8c0.png)
Here, this popup shows once per modpack
