### ISSUE TITLE
Crash but idk why

### ISSUE THREAD

**Issue by tiarnia** [APengu/LostThaumaturgy#5]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1 (1).jar)
  AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-anarchy.jar)
  BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.368.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  ForgelinPlugin (Forgelin-1.4.2.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  RebornCoreASM (RebornCore-1.11.2-2.14.2.94-universal.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  LoadingPlugin (HardcoreDarkness-MC1.11.2-1.9.jar)
  HammerCoreCore (HammerCore_1.11.2-1.6.0.jar)
  LoadingPlugin (Quark-r1.2-91.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 5/12/17 8:11 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lost Thaumaturgy (lostthaumaturgy)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.pengu.lostthaumaturgy.init.BlocksLT
	at com.pengu.lostthaumaturgy.items.ItemMultiMaterial.registerOD(ItemMultiMaterial.java:51)
	at com.pengu.lostthaumaturgy.LostThaumaturgy.preInit(LostThaumaturgy.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:100)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 57498128 bytes (54 MB) / 410845184 bytes (391 MB) up to 6357254144 bytes (6062 MB)
	JVM Flags: 10 total; -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -Xmx6096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2294 106 mods loaded, 106 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forgemod.jar) 
	UCH	forge{13.20.0.2294} [Minecraft Forge] (forgemod.jar) 
	UCH	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCH	backpacks16840{3.1.9} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.9.jar) 
	UCH	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCH	actuallyadditions{1.11.2-r107} [Actually Additions] (ActuallyAdditions-1.11.2-r107.jar) 
	UCH	aether_legacy{v1.4.1} [Aether Legacy] (aether_legacy-1.11.2-1.0.jar) 
	UCH	baubles{1.4.4} [Baubles] (Baubles-1.11-1.4.4.jar) 
	UCH	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.1.jar) 
	UCH	flyringbaublemod{0.2.4_1.11.2-6570ea2} [AngelRing 2 Bauble] (angelRingToBauble-1.11.2-0.2.4.24+6570ea2.jar) 
	UCH	applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar) 
	UCH	jei{4.3.3.270} [Just Enough Items] (jei_1.11.2-4.3.3.270.jar) 
	UCH	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCH	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCH	aroma1997sdimension{1.0} [Aroma1997sDimension] (Aroma1997s-Dimensional-World-1.11.2-1.3.0.0.jar) 
	UCH	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13 (1).jar) 
	UCH	psi{r1.1-47} [Psi] (Psi-r1.1-47.jar) 
	UCH	quark{r1.2-91} [Quark] (Quark-r1.2-91.jar) 
	UCH	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4 (1).jar) 
	UCH	betterbedrockgen{6.0.1} [BetterBedrockGen] (BBG-6.0.1.jar) 
	UCH	bdlib{1.13.2.7} [BD Lib] (bdlib-1.13.2.7-mc1.11.2.jar) 
	UCH	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.11.2-1.1.7.jar) 
	UCH	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
	UCH	guideapi{1.11.2-2.1.1-52} [Guide-API] (Guide-API-1.11.2-2.1.1-52.jar) 
	UCH	bloodmagic{1.11-2.1.9-78} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.9-78.jar) 
	UCH	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.11-1.5.1 (1).jar) 
	UCH	bookshelf{1.5.0.368} [Bookshelf] (Bookshelf-1.11.2-1.5.0.368.jar) 
	UCH	bookshelfapi{5.0.0} [Bookshelf] (Bookshelf-API-1.11.2-5.0.0-B96.jar) 
	UCH	botania{r1.9-343} [Botania] (Botania r1.9-343.jar) 
	UCH	buildersguides{1.11.2-0.1.0} [Builders Guides] (buildersguides-1.11.2-0.1.0.jar) 
	UCH	ceramics{1.11.2-1.2.0} [Ceramics] (Ceramics-1.11.2-1.2.0.jar) 
	UCH	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2 (1).jar) 
	UCH	chesttransporter{2.7.8} [Chest Transporter] (ChestTransporter-1.11.2-2.7.8.jar) 
	UCH	chisel{MC1.11.2-0.0.10.14} [Chisel] (Chisel-MC1.11.2-0.0.10.14.jar) 
	UCH	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCH	cyclopscore{0.10.2} [Cyclops Core] (CyclopsCore-1.11.2-0.10.2.jar) 
	UCH	commoncapabilities{1.3.2} [CommonCapabilities] (CommonCapabilities-1.11.2-1.3.2.jar) 
	UCH	cookingforblockheads{5.3.20} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.20.jar) 
	UCH	darkutils{1.2.0.126} [Dark Utilities] (DarkUtilities-1.11.2-1.2.0.126.jar) 
	UCH	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCH	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.0.112-universal.jar) 
	UCH	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCH	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCH	etlunar{1.11.2-0.11.0c} [ET Lunar] (etlunar-1.11.2-0.11.0c.jar) 
	UCH	zerocore{1.11.2-0.1.0.5} [Zero CORE] (zerocore-1.11.2-0.1.0.5.jar) 
	UCH	bigreactors{1.11.2-0.4.5.28} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.28.jar) 
	UCH	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCH	sonarcore{4.0.0} [SonarCore] (SonarCore-1.11.2-4.0.0 (1).jar) 
	UCH	fluxnetworks{2.0.0} [FluxNetworks] (FluxNetworks-1.11.2-2.0.0.jar) 
	UCH	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-anarchy.jar) 
	UCH	forestry{5.3.3.96} [Forestry] (forestry_1.11.2-5.3.3.96.jar) 
	UCH	forgelin{1.4.2} [Forgelin] (Forgelin-1.4.2.jar) 
	UCH	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.2.jar) 
	UCH	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.0.jar) 
	UCH	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCH	hammercore{1.6.0} [Hammer Core] (HammerCore_1.11.2-1.6.0.jar) 
	UCH	hardcoredarkness{1.9} [Hardcore Darkness] (HardcoreDarkness-MC1.11.2-1.9.jar) 
	UCH	helpfixer{1.4+17} [HelpFixer] (HelpFixer-1.11-1.4+17.jar) 
	UCH	waila{1.8.13} [Waila] (Hwyla-1.8.13-B26_1.11.jar) 
	UCH	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCH	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCH	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCH	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.jar) 
	UCE	lostthaumaturgy{2b} [Lost Thaumaturgy] (LostThaumaturgy_1.11.2-2b.jar) 
	UCH	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCH	missing_pieces{4.1.1} [Missing Pieces] (missing_pieces-1.11-4.1.3.jar) 
	UCH	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCH	mysticalagriculture{1.5.2} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.5.2c.jar) 
	UCH	mysticalagradditions{1.0.2} [Mystical Agradditions] (mysticalagradditions[1.11.2]-1.0.2.jar) 
	UCH	natura{1.11.2-4.2.0.11} [Natura] (natura-1.11.2-4.2.0.11.jar) 
	UCH	tconstruct{1.11.2-2.7.0.9} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.9.jar) 
	UCH	neotech{5.0.0} [NeoTech] (Neotech-1.11.2-5.0.0.jar) 
	UCH	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1 (1).jar) 
	UCH	nmsot{1.2.0-mc1.11.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar) 
	UCH	notenoughwands{1.5.4} [Not Enough Wands] (notenoughwands-1.1x-1.5.4.jar) 
	UCH	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCH	shetiphiancore{3.4.4} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.4.jar) 
	UCH	platforms{1.3.4} [Platforms] (platforms-1.11.0-1.3.4.jar) 
	UCH	prefab{1.2.0.6} [Prefab] (prefab-1.2.0.6.jar) 
	UCH	reborncore{2.14.2.94} [Reborn Core] (RebornCore-1.11.2-2.14.2.94-universal.jar) 
	UCH	quantumstorage{4.1.3} [QuantumStorage] (QuantumStorage-1.11.2-4.1.3.jar) 
	UCH	randomthings{3.8.1} [Random Things] (RandomThings-MC1.11.2-3.8.1.jar) 
	UCH	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4 (1).jar) 
	UCH	reborncore-mcmultipart{2.14.2.94} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.14.2.94-universal.jar) 
	UCH	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCH	refinedstorage{1.4.4} [Refined Storage] (refinedstorage-1.4.4.jar) 
	UCH	xreliquary{1.11.2-1.3.3.653} [Reliquary] (Reliquary-1.11.2-1.3.3.653.jar) 
	UCH	rftools{6.00} [RFTools] (rftools-1.1x-6.00 (1).jar) 
	UCH	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.1x-1.6.8.jar) 
	UCH	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55 (1).jar) 
	UCH	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11.2-3.7.5.jar) 
	UCH	simplegenerators{1.11.2-0.11.0a} [Simple Generators] (simplegenerators-1.11.2-0.11.0a.jar) 
	UCH	solarfluxreborn{2.15r} [Solar Flux Reborn] (SolarFluxReborn_1.11.2-2.15r.jar) 
	UCH	storagedrawers{1.11.2-4.2.3} [Storage Drawers] (StorageDrawers-1.11.2-4.2.3.jar) 
	UCH	substratum{1.9.2.0} [Substratum] (Substratum-1.11.2-1.9.2.0.jar) 
	UCH	tp{2.2.0-Hotfix} [Tiny Progressions] (tinyprogressions-1.11.2-2.2.0-Hotfix.jar) 
	UCH	torchmaster{1.3.2.35} [TorchMaster] (torchmaster_1.11.2-1.3.2.35.jar) 
	UCH	wanionlib{1.11.2-1.0} [WanionLib] (WanionLib-1.11.2-1.0.jar) 
	UCH	wawla{2.4.0.231} [What Are We Looking At] (Wawla-1.11.2-2.4.0.231.jar) 
	UCH	weirdinggadget{1.0} [The Weirding Gadget] (weirdinggadget-1.11.2-1.0.1-universal.jar) 
	UCH	woot{1.11.2-0.2.0} [Woot] (woot-1.11.2-0.2.0.jar) 
	UCH	yabba{1.11.2-0.5.0} [YABBA] (YABBA-1.11.2-0.5.0.jar) 
	UCH	unidict{1.11.2-1.0} [UniDict] (UniDict-1.11.2-1.0.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.11-1.5.1 (1).jar)
  lumien.bloodmoon.asm.ClassTransformer
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.368.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  lumien.randomthings.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  shetiphian.core.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.4.2.jar)
  
ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  team.chisel.common.asm.ChiselTransformer
RebornCoreASM (RebornCore-1.11.2-2.14.2.94-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  
SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
LoadingPlugin (HardcoreDarkness-MC1.11.2-1.9.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
HammerCoreCore (HammerCore_1.11.2-1.6.0.jar)
  com.mrdimka.hammercore.asm.HammerCoreTransformer
LoadingPlugin (Quark-r1.2-91.jar)
  vazkii.quark.base.asm.ClassTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
  brad16840.common.asm.ClassTransformer
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.11.2-r107.jar
		* AppleCoreAPI (2.2.0) from AppleCore-mc1.11.2-2.1.2.jar
		* Baubles|API (1.4.0.2) from Baubles-1.11-1.4.4.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.11.2-0.4.5.28.jar
		* bloodmagic|API (1.11-2.1.9-78) from BloodMagic-1.11-2.1.9-78.jar
		* BotaniaAPI (86) from Botania r1.9-343.jar
		* chesttransporter|api (1) from ChestTransporter-1.11.2-2.7.8.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.11.2-0.0.10.14.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.11.2-0.0.10.14.jar
		* CoFHAPI (1.8.9R1.2.0B1) from SolarFluxReborn_1.11.2-2.15r.jar
		* cofhapi (1.6.0) from zerocore-1.11.2-0.1.0.5.jar
		* cofhapi|block (1.6.0) from zerocore-1.11.2-0.1.0.5.jar
		* cofhapi|core (1.6.0) from zerocore-1.11.2-0.1.0.5.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from SolarFluxReborn_1.11.2-2.15r.jar
		* cofhapi|energy (1.4.0) from extrautils2-1.11.2-1.4.1.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11 (1).jar
		* cofhapi|item (1.6.0) from zerocore-1.11.2-0.1.0.5.jar
		* cofhapi|tileentity (1.6.0) from zerocore-1.11.2-0.1.0.5.jar
		* cofhapi|util (1.6.0) from zerocore-1.11.2-0.1.0.5.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.11.2-1.3.2.jar
		* compatlayer (0.2.8) from compatlayer-1.11.2-0.2.8.jar
		* environmentaltech-api (1.11.2-0.11.0d) from environmentaltech-1.11.2-0.11.0d.jar
		* fluxapi (1.0) from FluxNetworks-1.11.2-2.0.0.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|farming (2.2.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.3.96.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.3.96.jar
		* Guide-API|API (2.0.0) from Guide-API-1.11.2-2.1.1-52.jar
		* jeresources|API (0.6.2.104) from JustEnoughResources-1.11.2-0.6.2.104.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* JustEnoughItemsAPI (4.12.0) from jei_1.11.2-4.3.3.270.jar
		* mcjtylib_ng (2.3.11) from mcjtylib-1.1x-2.3.11 (1).jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.11.2.jar
		* PsiAPI (4) from Psi-r1.1-47.jar
		* reborncoreAPI (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Fuel (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Power (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Recipe (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Tile (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.4.4.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.4.4.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.3.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.3.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.4.4.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.3.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.4.4.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.3.jar
		* valkyrielib.api (1.11.2-0.11.0b) from valkyrielib-1.11.2-0.11.0c.jar
		* WailaAPI (1.3) from Hwyla-1.8.13-B26_1.11.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.5.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.5.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.5.jar
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.14.2.94
		Mixin Status: 1
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by APengu** [comment]
Fixed.
