### ISSUE TITLE
Better Foliage Compatibility

### ISSUE THREAD

**Issue by kenijey** [APengu/LostThaumaturgy#6]
https://github.com/octarine-noise/BetterFoliage/issues/129

**Comment by APengu** [comment]
This  is on their end, I hope. I don't see any issues on my side.

**Comment by APengu** [comment]
The log issue is on my side though

**Comment by APengu** [comment]
![image](https://cloud.githubusercontent.com/assets/10291214/26064876/e7561c5c-399a-11e7-8e7a-51a0221224d4.png)

Here, fixed log rounding bug. I had no crashed yet btw.

**Comment by kenijey** [comment]
you fixed it without need betterfoliage update? great job. thanks!

**Comment by APengu** [comment]
Yeah, but that crash was because of corals

**Comment by kenijey** [comment]
oh you mean that crash, yeah i don't know what causes that, is it only betterfoliage sided?

**Comment by APengu** [comment]
yepp

**Comment by kenijey** [comment]
okay than we are waiting @octarine-noise to the scene of the film :)
