### ISSUE TITLE
[CoS] [1.11.2] HammerCore 1.7.2

### ISSUE THREAD

**Issue by drakray** [APengu/LostThaumaturgy#7]
Crash on Start
https://pastebin.com/2kTv349K
May be caused by 1.7.1 math change?

PLT 6b
Forge 2308

**Comment by APengu** [comment]
I know this. it is because i deleted experimental classes and they are used in PLT 6b.

**Comment by drakray** [comment]
do PLT 7b use HC 1.7.4?

**Comment by APengu** [comment]
Yes
